sudo: required
services:
  - docker

before_install:
  - docker build -t kalsabag/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kalsabag/react-test npm test -- --coverage

after_success:
  - docker build -t kalsabag/multi-client ./client
  - docker build -t kalsabag/multi-nginx ./nginx
  - docker build -t kalsabag/multi-server ./server
  - docker build -t kalsabag/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  #take those images and push to docker hub
  - docker push kalsabag/multi-client
  - docker push kalsabag/multi-nginx
  - docker push kalsabag/multi-server
  - docker push kalsabag/multi-worker